### PR TITLE
Added forced client certificate validation

### PR DESCRIPTION
**Pull request by sebt3**
Hi,

A few notes about this pull request.
The added else block is very usefull for debuging any ssl issues. It should probably either come in a #ifdef block or a configurable "if".
ssl_session_ctx_id could be randomized, although as far as I know there's no security issue at having a const this way.
the SSL_CTX_set_session_id_context line enable SSL session caching. It is mandatory for client certification. Performance wise it sound wise to enable it even if not using client cert (so the long ssl handshake is skipped)
your verify_file is then used to match the client certificate.

### CODE REVIEW

**Comment by eidheim** [comment]
Thank you. I would have to read up on this, it will probably take a few days before I find the time.

**Comment by sebt3** [comment]
Yes totally expected. We're touching security here so a causious look is mandatory.
Take your time. I've debugged and traced this using wireshark and chrome debugger.
I'll do the same thing on the client side too (if required, I havent had a look yet). Pull request will come next week at best for this.

**Comment by sebt3** [comment]
geez, the last commit was aimed at an *other* pull request.
Anyway, I've just added this feature to my code and I though about giving back somehow. 
Only adding it to the https example as it actually depend on openssl. Any other hashing could be used.

**Comment by sebt3** [comment]
up ?

**Comment by eidheim** [comment]
Sorry! I've been quite busy lately, but hopefully I'll find some time very soon!

**Comment by eidheim** [comment]
I created this quick and maybe dirty (I'll study it more in detail later) solution instead that I think does the same (as the original PR request). On the plus side, we might be able to do this through boost.asio alone without the need of messing with OpenSSL:
```c++
diff --git a/server_https.hpp b/server_https.hpp
index bbd7f79..3bc1494 100644
--- a/server_https.hpp
+++ b/server_https.hpp
@@ -9,17 +9,27 @@ namespace SimpleWeb {
     
     template<>
     class Server<HTTPS> : public ServerBase<HTTPS> {
+        bool verify_certificate;
+        
     public:
         Server(unsigned short port, size_t num_threads, const std::string& cert_file, const std::string& private_key_file,
                 long timeout_request=5, long timeout_content=300,
-                const std::string& verify_file=std::string()) : 
-                ServerBase<HTTPS>::ServerBase(port, num_threads, timeout_request, timeout_content), 
+                const std::string& verify_file=std::string(), bool verify_certificate=false) : 
+                ServerBase<HTTPS>::ServerBase(port, num_threads, timeout_request, timeout_content),
+                verify_certificate(verify_certificate),
                 context(boost::asio::ssl::context::tlsv12) { // 2016/08/13 only use tls12, see https://www.ssllabs.com/ssltest
             context.use_certificate_chain_file(cert_file);
             context.use_private_key_file(private_key_file, boost::asio::ssl::context::pem);
             
             if(verify_file.size()>0)
                 context.load_verify_file(verify_file);
+            else
+                context.set_default_verify_paths();
+            
+            if(verify_file.size()>0 || verify_certificate)
+                context.set_verify_mode(boost::asio::ssl::verify_peer | boost::asio::ssl::verify_fail_if_no_peer_cert);
+            else
+                context.set_verify_mode(boost::asio::ssl::verify_none);
         }
 
     protected:
@@ -40,15 +50,37 @@ namespace SimpleWeb {
                     boost::asio::ip::tcp::no_delay option(true);
                     socket->lowest_layer().set_option(option);
                     
-                    //Set timeout on the following boost::asio::ssl::stream::async_handshake
-                    auto timer=get_timeout_timer(socket, timeout_request);
-                    (*socket).async_handshake(boost::asio::ssl::stream_base::server, [this, socket, timer]
-                            (const boost::system::error_code& ec) {
-                        if(timer)
-                            timer->cancel();
-                        if(!ec)
-                            read_request_and_content(socket);
-                    });
+                    if(!verify_certificate) {
+                        auto timer=get_timeout_timer(socket, timeout_request);
+                        (*socket).async_handshake(boost::asio::ssl::stream_base::server, [this, socket, timer]
+                                (const boost::system::error_code& ec) {
+                            if(timer)
+                                timer->cancel();
+                            if(!ec)
+                                read_request_and_content(socket);
+                        });
+                    }
+                    else {
+                        auto ip_address=socket->lowest_layer().remote_endpoint().address().to_string();
+                        auto port=socket->lowest_layer().remote_endpoint().port();
+                        boost::asio::ip::tcp::resolver::query query(ip_address, std::to_string(port));
+                        auto resolver=std::make_shared<boost::asio::ip::tcp::resolver>(*io_service);
+                        resolver->async_resolve(query, [this, socket, resolver]
+                                               (const boost::system::error_code &ec, boost::asio::ip::tcp::resolver::iterator it){
+                            if(!ec) {
+                                socket->set_verify_callback(boost::asio::ssl::rfc2818_verification(it->host_name()));
+                                
+                                auto timer=get_timeout_timer(socket, timeout_request);
+                                (*socket).async_handshake(boost::asio::ssl::stream_base::server, [this, socket, timer]
+                                        (const boost::system::error_code& ec) {
+                                    if(timer)
+                                        timer->cancel();
+                                    if(!ec)
+                                        read_request_and_content(socket);
+                                });
+                            }
+                        });
+                    }
                 }
             });
         }
```

Note that I'm going to clean up the constructors at some point and deprecate the current ones.

**Comment by sebt3** [comment]
Err nope. It doesnt do the same thing.
The rfc2818_verification is never expected to be done on the client. so this is actually bogus.
Before my patch, your code never actually verify if the client match anything in the "verify_file" because the client never send it's certificate. Because the server never asked the client to provide one.
All my patch was doing is making the SSL server to request the client key so it can actually be checked.

You can test this on your side easyly. Use your https test providing it a verify_file. Browse the service. your browser dont ask you for a key.
Now apply my patch, rebuild. Your browser ask you which key to provide (if he knows any, else the connection will just fail)

**Comment by eidheim** [comment]
I think I found the part where it is stated that hostname verification should not be done https://tools.ietf.org/html/rfc2818#section-3.2. Then the diff would be:
```diff
diff --git a/server_https.hpp b/server_https.hpp
index bbd7f79..3107be9 100644
--- a/server_https.hpp
+++ b/server_https.hpp
@@ -12,7 +12,7 @@ namespace SimpleWeb {
     public:
         Server(unsigned short port, size_t num_threads, const std::string& cert_file, const std::string& private_key_file,
                 long timeout_request=5, long timeout_content=300,
-                const std::string& verify_file=std::string()) : 
+                const std::string& verify_file=std::string(), bool verify_certificate=false) : 
                 ServerBase<HTTPS>::ServerBase(port, num_threads, timeout_request, timeout_content), 
                 context(boost::asio::ssl::context::tlsv12) { // 2016/08/13 only use tls12, see https://www.ssllabs.com/ssltest
             context.use_certificate_chain_file(cert_file);
@@ -20,6 +20,13 @@ namespace SimpleWeb {
             
             if(verify_file.size()>0)
                 context.load_verify_file(verify_file);
+            else
+                context.set_default_verify_paths();
+            
+            if(verify_file.size()>0 || verify_certificate)
+                context.set_verify_mode(boost::asio::ssl::verify_peer | boost::asio::ssl::verify_fail_if_no_peer_cert);
+            else
+                context.set_verify_mode(boost::asio::ssl::verify_none);
         }
 
     protected:
```

And I do get the "The website localhost requires a client certificate" in a browser when using the code above. The question is if the OpenSSL functions are needed, or it is enough to add the above changes.

**Comment by sebt3** [comment]
The "else" block in my patch is completely optional. Indeed.

In my tests, the "SSL_CTX_set_session_id_context(context.native_handle(), &ssl_session_ctx_id, sizeof(ssl_session_ctx_id));" line become mandatory at the second connection of the client...
Every browser (firefox and chrome included) expect the SSL cache feature without even negociating for it. if client certificate is requested. So once the browser negociated an SSL connection with a server, on the second (and next) connections it will switch to encrypted data directly without any SSL negociation using crypto keys of the initial connection. 
If the server doesnt cache the crypto keys on his side, then any other connection from the browser will fail as the server will receive encrypted data it cannot decrypt.
So that lines is mandatory if client certificate is requested. 

I would also argue that it would be a nice feature even without client certification request as it is then negociated, and can boost connection time significantly (as the certificate are not exchanged for any later connection).

**Comment by eidheim** [comment]
I think the option is can be set with boost::asio::ssl::verify_client_once:
```c++
context.set_verify_mode(boost::asio::ssl::verify_peer | boost::asio::ssl::verify_fail_if_no_peer_cert |
                                        boost::asio::ssl::verify_client_once);
```

**Comment by eidheim** [comment]
Next, if one does use `verify_file` on the server, I guess one also wants to verify the client certificate. The question is if there are cases where one would set verify_file to "", and still want to verify the client certificate. That is, are there cases where a client has a signed certificate from a 3. party verified CA?

**Comment by sebt3** [comment]
Sound like it to me.
and indeed I agree. I only used this boolean so your code was still backward compatible. Never sayed it was a great idea :P

**Comment by sebt3** [comment]
Err actually nope. It doesnt work.
With boost::asio::ssl::verify_client_once and the SSL_CTX_set_session_id_context line commented out. 

Every next request failed and SSL on the server say : "SSL routines:ssl_get_prev_session:session id context uninitialized". If you want to see the SSL error, use the "else" block from my patch.

**Comment by eidheim** [comment]
Server is actually missing a decent error handling/reporting, but I'll fix that Tomorrow. I'll look into the verify_client_once problem as well. What OS and boost version are you using? Just thinking that it might be related to this, though I have not tested it myself yet on the OS'es I work on.

**Comment by sebt3** [comment]
I'm currently linking with boost 1.62.0 on an up to date debian sid. But I tried with 1.61, 1.58 too.

**Comment by eidheim** [comment]
I'll work on the error reporting later, but setting the session_id_context should maybe be done somewhat like this:
```diff
diff --git a/server_https.hpp b/server_https.hpp
index bbd7f79..4416b3c 100644
--- a/server_https.hpp
+++ b/server_https.hpp
@@ -3,12 +3,15 @@
 
 #include "server_http.hpp"
 #include <boost/asio/ssl.hpp>
+#include <random>
+#include <openssl/ssl.h>
 
 namespace SimpleWeb {
     typedef boost::asio::ssl::stream<boost::asio::ip::tcp::socket> HTTPS;    
     
     template<>
     class Server<HTTPS> : public ServerBase<HTTPS> {
+        unsigned char session_id_context[SSL_MAX_SSL_SESSION_ID_LENGTH];
     public:
         Server(unsigned short port, size_t num_threads, const std::string& cert_file, const std::string& private_key_file,
                 long timeout_request=5, long timeout_content=300,
@@ -18,8 +21,22 @@ namespace SimpleWeb {
             context.use_certificate_chain_file(cert_file);
             context.use_private_key_file(private_key_file, boost::asio::ssl::context::pem);
             
-            if(verify_file.size()>0)
+            if(verify_file.size()>0) {
                 context.load_verify_file(verify_file);
+                context.set_verify_mode(boost::asio::ssl::verify_peer | boost::asio::ssl::verify_fail_if_no_peer_cert);
+                
+                // From https://wiki.openssl.org/index.php/Manual:SSL_CTX_set_session_id_context(3):
+                // "... each application must set its own session id context sid_ctx which is used to distinguish the contexts and is stored in exported sessions"
+                auto port_str=std::to_string(port)+' ';
+                std::random_device rd;
+                for(size_t c=0;c<SSL_MAX_SSL_SESSION_ID_LENGTH;++c) {
+                    if(c<port_str.size())
+                        session_id_context[c]=static_cast<unsigned char>(port_str[c]);
+                    else
+                        session_id_context[c]=static_cast<unsigned char>(rd());
+                }
+                SSL_CTX_set_session_id_context(context.native_handle(), session_id_context, SSL_MAX_SSL_SESSION_ID_LENGTH);
+            }
         }
 
     protected:
```

What do you think?

**Comment by eidheim** [comment]
By the way, it seems that boost::asio never initialise its internal session id context.

**Comment by eidheim** [comment]
I added `boost::asio::ssl::verify_client_once` just to be on the safe side, so the diff becomes:
```diff
diff --git a/server_https.hpp b/server_https.hpp
index bbd7f79..c9c52c3 100644
--- a/server_https.hpp
+++ b/server_https.hpp
@@ -3,12 +3,15 @@
 
 #include "server_http.hpp"
 #include <boost/asio/ssl.hpp>
+#include <random>
+#include <openssl/ssl.h>
 
 namespace SimpleWeb {
     typedef boost::asio::ssl::stream<boost::asio::ip::tcp::socket> HTTPS;    
     
     template<>
     class Server<HTTPS> : public ServerBase<HTTPS> {
+        unsigned char session_id_context[SSL_MAX_SSL_SESSION_ID_LENGTH];
     public:
         Server(unsigned short port, size_t num_threads, const std::string& cert_file, const std::string& private_key_file,
                 long timeout_request=5, long timeout_content=300,
@@ -18,8 +21,23 @@ namespace SimpleWeb {
             context.use_certificate_chain_file(cert_file);
             context.use_private_key_file(private_key_file, boost::asio::ssl::context::pem);
             
-            if(verify_file.size()>0)
+            if(verify_file.size()>0) {
                 context.load_verify_file(verify_file);
+                context.set_verify_mode(boost::asio::ssl::verify_peer | boost::asio::ssl::verify_fail_if_no_peer_cert |
+                                        boost::asio::ssl::verify_client_once);
+                
+                // From https://wiki.openssl.org/index.php/Manual:SSL_CTX_set_session_id_context(3):
+                // "... each application must set its own session id context sid_ctx which is used to distinguish the contexts and is stored in exported sessions"
+                auto port_str=std::to_string(port)+' ';
+                std::random_device rd;
+                for(size_t c=0;c<SSL_MAX_SSL_SESSION_ID_LENGTH;++c) {
+                    if(c<port_str.size())
+                        session_id_context[c]=static_cast<unsigned char>(port_str[c]);
+                    else
+                        session_id_context[c]=static_cast<unsigned char>(rd());
+                }
+                SSL_CTX_set_session_id_context(context.native_handle(), session_id_context, SSL_MAX_SSL_SESSION_ID_LENGTH);
+            }
         }
 
     protected:
```

**Comment by eidheim** [comment]
I realise that port_str (renaming it to context_str) should include the address as well in cases where a server has several network cards. I will move the creation of session_id_context and SSL_CTX_set_session_id_context to accept() then and take care it is run only once.

**Comment by eidheim** [comment]
And then it might not be necessary to add the random bytes at the end of the array.

**Comment by sebt3** [comment]
This is all good to me. Thanks a lot, your implementation is way better than mine :)
I'm looking forward your implementation of error handling.
Feautres I'ld love to see there :
- take an optional std::function for reporting
- no std::function provided, nothing done (just like now)
- provide a default function that output evrything to stdout ;)

What do you think about my other patch in this PR (implementing a support for HTTP 304 as a demo in the https example) ?

**Comment by eidheim** [comment]
Thank you as well! The final commit regarding client certificate verification can be seen above. 

We think alike with regards to the future error handling solution:)

I'll have a look at your other patch Tomorrow or so, but after I implement the error handling most likely Tomorrow.

**Comment by eidheim** [comment]
I added error reporting in https://github.com/eidheim/Simple-Web-Server/commit/eef8a108499ba6f27fd578d2cde9d587937fc6b7

**Comment by sebt3** [comment]
You should probably use "std::make_shared<Request>(...)" instead of "std::shared_ptr<Request>(new Request(...))"
Otherwise nicely done. thanks again. I'll update, test and report back here this evening (early morning here)

**Comment by eidheim** [comment]
Great, sadly though one can't use `std::make_shared` when constructors are not public.

**Comment by sebt3** [comment]
arf, yeah, that...
Anyway, tested and working well.
My project is back to your main-line once more :)
Thanks a lot, that's a great feature that you should advertise somehow in one of your examples ;)
Speaking about example, I could rewrite my HTTP caching example using boost::hash instead of sha256 from openssl. The hash is to identify the file, there's no security there, so any valid hashing method can do. and sha256 is far from fast :P

**Comment by eidheim** [comment]
It seems I have to read up on HTTP caching as well, but your commit looks good. It looks like boost::hash is similar to std::hash? However, these hashes are only 64 bit (on 64 bit systems), although MD5 is commonly used for file hashes if I'm not mistaken, and is 128 bit no matter which system you are on. Have a look at https://github.com/eidheim/Simple-WebSocket-Server/blob/master/crypto.hpp as well, there are some simplifications that you can do by using the MD5 function directly instead of doing Init/Update/Final. Your implementation is slightly better though since you are using an array as output for the hash instead of a string (and string::resize does initialization of new values).

**Comment by eidheim** [comment]
Or maybe just stick to std::string instead of arrays since it's more modern C++ and the overhead should be minimal. Not sure. Also then one would not worry about the stack (there have been problems prior with large stack allocations together with boost.asio).

**Comment by sebt3** [comment]
While 64bit seams a bit low. It would still work as far as caching is concerned. The probability that an edited file have the same hash before and after the edit is damn low. but sure it is higher than using a 256bits hash.
Your comment seems to suggest that boost::hash and std::hash use 32bits hash on 32bits system. And that would be problematic.
Though I havent found a way to compute an md5 hash without using openssl (in the same vein of my sha256 usage).
Your crypto class looks good, import it here too :P Although, SHA512 is just silly (it doesnt improve anything security wise but it significantly more intensive) ;) Once imported here, using your md5 function sound the way to go (after reading the whole file).

As you please, you tell me ;)

**Comment by eidheim** [comment]
I added crypto.hpp in https://github.com/eidheim/Simple-Web-Server/commit/5c5a1f78b23bfe282ff29fdecfe778580222701f. My only worry now is that someone people use Simple-Web-Server without having OpenSSL installed (for HTTP only that is). We should maybe keep it this way, but that would require an `#ifdef...` block in http_examples...

I'll also add some common key stretching algorithms like PBKDF2 to crypto.hpp. I also added Crypto::to_hex_string that you can use if you'd like.

**Comment by sebt3** [comment]
Will come clean with a new one in a few

**Pull request closed without merging**
