### PR TITLE
compile clean with gcc 4.6.3

### PR DESCRIPTION
**Pull request by ntadas**
see https://github.com/eidheim/Simple-Web-Server/issues/78

### CODE REVIEW

**Comment by eidheim** [comment]
Thank you, but could you pull the latest changes before making the PR? This is due to the conflicts that need to be resolved with this PR.

**Comment by ntadas** [comment]
Sure. I'll do it later today.

**Comment by ntadas** [comment]
I've already created a new pull request, this one can be rejected

**Comment by eidheim** [comment]
Thank you!

**Pull request closed without merging**
