### PR TITLE
Added client support for HTTP&HTTPS proxy requests.

### PR DESCRIPTION
**Pull request by classix-do**
* new method: Client<HTTP/HTTPS>::proxy_request(...)

### CODE REVIEW

**Comment by eidheim** [comment]
Thank you, but the diff is somewhat strange?

**Comment by classix-do** [comment]
Yes, I noticed it too, while merging the changes. I don't know why, but I guess my editor screwed up the whitespaces or the encoding. I'll try to fix it.

**Comment by classix-do** [comment]
Should be fine now... My editor has set the line endings to Windows-style

**Comment by eidheim** [comment]
I agree that there is too much equal code in the two request method, but I'm thinking that one could set the proxy parameters at the Client-constructor instead. What do you think? Also, if possible, one could use one string to specify host:port like done at the moment when specifying the server to connect to.

**Comment by classix-do** [comment]
I agree. It's more logical to set the proxy details together with the target host in the client's constructor. This means adding an overload to the `ClientBase`, `Client<HTTP>` and `Client<HTTPS>` constructor and remove the `proxy_request()` method from the client's interface. 

The `request()` would then create a proxy request if a proxy-connection has been passed to the constructor and would fall back to a regular HTTP(S) request if none has been supplied.

I agree that the semantic for setting the proxy information should be the same, which is used to set the target host. 

So the additional constructors would look like this:

    ClientBase(const std::string& host_port, unsigned short default_port, const std::string& proxy_host_port, unsigned short default_proxy_port);
    Client<HTTP>(const std::string& server_port_path, const std::string& proxy_port);
    Client<HTTPS>(const std::string& server_port_path, const std::string& proxy_port);

I'll try to change the code accordingly tomorrow.

**Comment by classix-do** [comment]
What do you think of this implementation?

**Comment by eidheim** [comment]
Thank you, looks good, but I'll probably try to make some simplifications during the Weekend when I have time. Might also move the proxy setup to a Config class instead of using the constructors, I know more after I've looked into the changes in detail. Nevertheless, it's a good starting point!

**Comment by eidheim** [comment]
Merged https://github.com/eidheim/Simple-Web-Server/commit/743785b563f2371d9eb6fac971b130872459e777, I'll work on the rest in the Weekend.

**Comment by eidheim** [comment]
Just wanted to say that I've not forgotten this PR, and will have time to work on it in a couple of days.

**Comment by eidheim** [comment]
Proxy support has now been added to Client. Have not tested it though.

**Comment by classix-do** [comment]
Something seems to be missing for HTTPS proxy support.

To establish an HTTPS connection over an proxy, you have to first send an http CONNECT request. The Proxy then establishes a TCP tunnel (if responds with OK) and then you can start your SSL handshake over that TCP tunnel. That way the proxy cannot read your traffic.

As it is implemented right now, you simply start an HTTPS connection with the proxy and then use the regular proxy requests. This makes certificate validation impossible and lets the proxy see all your traffic, which would make https meaningless.

**Comment by eidheim** [comment]
Ok thank you, I'll add this as well Tomorrow morning. I just added a fix btw for the corrected paths when using proxy.

**Comment by eidheim** [comment]
Do you know if there are any default proxy ports for http and https?

**Comment by classix-do** [comment]
I searched a while but coudln't find a decisive answer in any forum.
Most HTTP-Proxies I found in proxy lists were using port 80 or 8080. While HTTPS proxies were mostly using port 8080 or 8088.

It seems as if port 8080 would be the default port for both protocols, which makes somewhat sense, because you need only one port to support proxying HTTP and HTTPS.

**Comment by eidheim** [comment]
Thank you. I added the CONNECT request, hopefully I got it right.

**Comment by eidheim** [comment]
Also fixed the request path when performing HTTPS client requests using a proxy server.

**Comment by eidheim** [comment]
Again, the code is untested, so feel free to let me know if it's working or not (both HTTP and HTTPS proxies).

**Comment by classix-do** [comment]
Ok, I'll run some tests as soon, as I find some time to do so, but the code changes look right and it should work.

**Comment by classix-do** [comment]
Sorry, that it took me so long, but I finally found the time to run your implementation through my proxy tests and the HTTP proxy works fine, but the HTTPS proxy requests are failing with uninitialized socket errors.

The first error occurs in [async_write() at line 87](https://github.com/eidheim/Simple-Web-Server/blob/master/client_https.hpp#L87) because you are writing the first HTTP CONNECT request to an **SSL** socket, which hasn't been initialized yet (no handshake). The HTTP request must be written to the **TCP** socket (one layer below).

This can be easily fixed by changing the line to:
```c++
boost::asio::async_write(socket->next_layer(), write_buffer, ...
```

But then the next uninitialized socket error occurrs when trying to read the response from the SSL socket via `request_read()` in [line 100](https://github.com/eidheim/Simple-Web-Server/blob/master/client_https.hpp#L100) which always reads from the [top layer of the client's socket](https://github.com/eidheim/Simple-Web-Server/blob/master/client_http.hpp#L251). 

This is not easily fixed, because `request_read()` needs to accept the socket to read from as parameter, which would affect:
* [line 251 in request_read](https://github.com/eidheim/Simple-Web-Server/blob/master/client_http.hpp#L251)
* [line 256 in request_read](https://github.com/eidheim/Simple-Web-Server/blob/master/client_http.hpp#L265)
* [line 296 in request_read_chunked](https://github.com/eidheim/Simple-Web-Server/blob/master/client_http.hpp#L296)
* [line 331 in request_read_chunked](https://github.com/eidheim/Simple-Web-Server/blob/master/client_http.hpp#L331)

That's why I had to introduce [this protected request()-overload](https://github.com/classix/Simple-Web-Server/blob/master/client_http.hpp#L140) in my suggested implementation.

**Comment by eidheim** [comment]
Thank you! The HTTPS proxy issue should hopefully be fixed in https://github.com/eidheim/Simple-Web-Server/commit/4606dbd85557fec53fba1ada50100a374810504c.

**Comment by classix-do** [comment]
Yes, 4606dbd has fixed the problem and my proxy tests are all green. 👍

**Comment by eidheim** [comment]
Great, and thank you again for contributing in implementing this feature!

**Pull request closed without merging**
