### PR TITLE
compile clean with gcc 4.6.3

### PR DESCRIPTION
**Pull request by ntadas**
related with https://github.com/eidheim/Simple-Web-Server/issues/78

### CODE REVIEW

**Comment by eidheim** [comment]
Just a quick question before merge. I see that the changes are only in server_http.hpp. Does that mean that the rest of the sources compile on g++ 4.6.3?

**Comment by ntadas** [comment]
I'm using only the servers didn't try the client.

**Comment by eidheim** [comment]
Thank you again!

**Comment by ntadas** [comment]
No prob. Thank you.

**Pull request merged**
