### PR TITLE
only use tlsv12, nothing older

### PR DESCRIPTION
**Pull request by moodboom**

### CODE REVIEW

**Comment by moodboom** [comment]
Thanks, sweet.  Shall we tackle the replace-RC4-with-AES problem?  I searched high and low and it seems like a bit of a vacuum to me in commonly-available libraries.  OpenSSL has AES, as does crypto++, but I haven't found a C/C++ https server that uses it.  Would be nice if Simple-Web-Server got there first.  Or am I barking up the wrong tree?

**Comment by eidheim** [comment]
I found only this: https://github.com/zaphoyd/websocketpp/blob/master/examples/echo_server_tls/echo_server_tls.cpp#L124. Here OpenSSL is used directly to disable RC4 I think (...:!RC4:...). See here for documentation of the command: https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_set_cipher_list.html. The SSL_CTX* is reached by doing `context.native_handle()` in https_server.hpp if I'm not mistaken. Although which ciphers should be included otherwise I'm not sure of, however, it should be possible to receive the cipher list from `SSL_CTX_get_ciphers` (https://www.openssl.org/docs/manmaster/ssl/SSL_get_ciphers.html), that is instead of hardcoding them like in https://github.com/zaphoyd/websocketpp/blob/master/examples/echo_server_tls/echo_server_tls.cpp#L124.

**Comment by moodboom** [comment]
Cool.  Here's the analysis that led me to think AES was the correct choice:

https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/

I'll try hardcoding a recommended cipher from there as the default and see what I get.  If that works, maybe we can provide a cipher option to the user?

Including support for HSTS seems to be the other important concern.

**Comment by eidheim** [comment]
Thank you, and thank you again for the interesting link. A cipher option would maybe be nice, or else we could add good default ones by modifying the current default openssl ciphers maybe. I guess we also have to consider what ciphers have to be available to support most web browsers. 

Might be that RC4 is disabled by default in newer versions of openssl for instance too? I guess they stay pretty current with which ciphers should be used and not? I'll try look into this too when I have time Wednesday or so.

**Comment by eidheim** [comment]
I think the cipher string input to SSL_CTX_set_cipher_list can be "DEFAULT:!RC4" to disable RC4. See the description of DEFAULT under CIPHER STRINGS in https://www.openssl.org/docs/manmaster/apps/ciphers.html. Also from this page: "Note that RC4 based ciphersuites are not built into OpenSSL by default (see the enable-weak-ssl-ciphers option to Configure)", so it might be based on the Linux distribution or version of openssl you are using?

**Comment by eidheim** [comment]
Setting the string input to SSL_CTX_set_cipher_list to "HIGH" might also be a good solution, at least if it excludes RC4.

**Pull request merged**
