### PR TITLE
Branch 1

### PR DESCRIPTION
**Pull request by waga-git**
Support "Connection: close" header.
A bit of improvement of parsing the protocol and version number of the request line.
Presrve the protocol of the request line in the "class Request" member value.

### CODE REVIEW

**Comment by eidheim** [comment]
Supporting connection close is great, but a quick question before I merge this: is storing the protocol really necessary?

**Comment by waga-git** [comment]
I think there is no code to check the protocol.
So that any 4 letters protocol will be accepted like this.

GET / ABCD/1.1

Storing the protocol provides the chance to check the protocol
to the programmers using this library.

Adding the checking code into "server_http.hpp" is another proposal.

**Comment by eidheim** [comment]
I guess we could make parse_request return false if the request is non-standard, or if the header contains Connection with value close. Then if parse_request is false, do a return and thus close the connection.

**Comment by waga-git** [comment]
The first case of returning false if the request is non-standard,
it sounds almost good because I have never seen that the protocol become other than 'HTTP'.
Currently the "parse_request" is defined as void func,
so the result of "parse_requet" should be preserved until write_response complete.

The second case of returning false if the request contains "Connection: close",
it sounds not good, because the request itself should process as
a valid request. And it is not able to classify from other errors like the first case.

**Comment by eidheim** [comment]
You're right. I'll look further on this Tomorrow hopefully.

**Pull request merged**
