### PR TITLE
support visual studio 2015

### PR DESCRIPTION
**Pull request by fivethreeo**

### CODE REVIEW

**Comment by eidheim** [comment]
Thank you, though I am not sure of the implications on other platforms, also the https_examples does not get compiled by default any more (I guess due to problems installing OpenSSL outside of MSYS2 on Windows). For instance, maybe the Boost_USE_... variables should be set only if MSVC is true? And one could remove REQUIRED from find_package(OpenSSL REQUIRED), and only compile https_examples if OpenSSL is found. Also did you need the date_time Boost component to compile in MSVC? 1.54.0 should include this component as well.

**Comment by fivethreeo** [comment]
Fixed the issues you mentioned:

To build for MSVC14:
 
mkdir builddir
cd builddir
cmake -G "Visual Studio 14 2015 Win64" -DBOOST_ROOT=C:\boost_1_59_0 -DBOOST_LIBRARYDIR=C:\boost_1_59_0\lib64-msvc-14.0 ..\Simple-Web-Server\

**Comment by fivethreeo** [comment]
Tests does not build

**Comment by eidheim** [comment]
Great, I'll have a look at it at Saturday, and fix the remaining issues.

**Comment by Allov** [comment]
I don't know where this PR stands as it is right now, but I can't get everything to compile. 

First, for anyone getting link errors, you need to add the boost library directory to the "Additional Library Directories" in the project:

Project properties > Configuration properties > Linker > Additional Library Directories > [add path to boost libraries (lib64-msvc-14.0)]

But, maybe that has to do with my boost installation?

Second, the `parse_test` project does not build because it's trying to create a `Request` and `Response` object and the constructor is private: `'SimpleWeb::ServerBase<SimpleWeb::HTTP>::Request::Request': cannot access private member declared in class 'SimpleWeb::ServerBase<SimpleWeb::HTTP>::Request'`.

Perhaps this is not up to date with latest project version? Any help is welcomed!

**Comment by eidheim** [comment]
I know some people are using this library in Visual Studio, though I'm working mainly on Posix platforms myself. Regarding the test, see https://github.com/eidheim/Simple-Web-Server/blob/master/tests/CMakeLists.txt#L1, that is when using clang++ or g++ the access control is disabled, which is nice sometimes when testing protected or private functions. My guess is that there is a similar option on MSVC.

The latest project version is the master branch. You should clone the master branch, if you have not done so already.

**Pull request merged**
