### PR TITLE
Issue/44/clean compile

### PR DESCRIPTION
**Pull request by drpatrik**
The code now compiles cleanly under OSX and Linux with Clang. There was a lot of long vs. size_t warnings that I solved with static_cast however it might be a better idea to use the correct type. I would also suggest at one point or another that member variables used by subclasses or aggregates are exposed through member functions instead.

### CODE REVIEW

**Comment by jeffreyscottgraham** [comment]
hiding the problem is not the best solution; if the code is going to be patched then can we improve it
instead?

**Comment by drpatrik** [comment]
I agree. However such a fix will be more intrusive then the fix I did. Its not my codebase so I do not want to changes that affects it too much. My development (emacs) is built around google code style which makes it a pain to use with a non, google-code-style, conformant code base.

**Comment by eidheim** [comment]
Thank you, but try avoid replacing whitespaces. They make the commit somewhat unreadable. I try not being strict with use of whitespace (as long as the current ones stay as is) to avoid making commits without real purpose. If everyone cleaned up their whitespaces it would not be a problem, but not all do. Sorry, but would you mind making a new PR?

Also, no need to change the current CMakeLists.txt, at least in my opinion, as it became somewhat bloated with the warning flags? That is, the goal is to get rid of warnings when using the headers in your and others projects. Maybe just replace -Wall with -Weverything for this repository? Then it's the same with gcc and clang as well (I would recommend using gcc for release build by the way; more optimised binaries). 

I agree with using the same type.

When it comes to setters and getters, I'm not a huge fan of such functions unless it is reasonable to assume that these are needed now or in the future. In larger projects, unneeded setters and getters are making the code much less readable in my opinion.

**Comment by drpatrik** [comment]
I have a macro in my editor that removes all trailing white-spaces when I save and this is what shows up in the diff where white-space has been removed. The only way for my do redo the pull-request is do get a fresh copy and start-over again turning off the macro in my editor.

**Comment by eidheim** [comment]
I'll accept it this time then:) I'm a bit busy Tonight, but hopefully Tomorrow I'll be able to go through the changes. Thank you again.

**Comment by drpatrik** [comment]
Thanks. I will ensure that I have the macro turned off the next time. Sorry for the inconvenience.

**Comment by eidheim** [comment]
I decided that `-Wshadow` restricts the programming style too much (I'm not a huge fan of the google style guide actually, I think I'm more partial to: https://github.com/isocpp/CppCoreGuidelines), but I made the following changes instead:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 836aa7c..41db0f6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,6 +1,6 @@
 cmake_minimum_required (VERSION 2.8)
 project (Simple-Web-Server)
-set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -O3 -Wall")
+set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -O3 -Weverything -Wno-shadow -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-weak-vtables -Wno-padded -Wno-unused-macros")
 
 if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
     if (CMAKE_CXX_COMPILER_VERSION VERSION_LESS 4.8)
diff --git a/client_http.hpp b/client_http.hpp
index 65eb63c..6b24a72 100644
--- a/client_http.hpp
+++ b/client_http.hpp
@@ -14,6 +14,8 @@ namespace SimpleWeb {
     template <class socket_type>
     class ClientBase {
     public:
+        virtual ~ClientBase() {}
+
         class Response {
             friend class ClientBase<socket_type>;
             
@@ -43,7 +45,7 @@ namespace SimpleWeb {
         private:
             boost::asio::streambuf content_buffer;
             
-            Response(): content(&content_buffer) {};
+            Response(): content(&content_buffer) {}
         };
         
         std::shared_ptr<Response> request(const std::string& request_type, const std::string& path="/", boost::string_ref content="",
@@ -86,7 +88,7 @@ namespace SimpleWeb {
                 corrected_path="/";
             
             content.seekp(0, std::ios::end);
-            size_t content_length=content.tellp();
+            auto content_length=content.tellp();
             content.seekp(0, std::ios::beg);
             
             boost::asio::streambuf write_buffer;
@@ -135,7 +137,7 @@ namespace SimpleWeb {
             }
             else {
                 host=host_port.substr(0, host_end);
-                port=(unsigned short)stoul(host_port.substr(host_end+1));
+                port=static_cast<unsigned short>(stoul(host_port.substr(host_end+1)));
             }
 
             asio_endpoint=boost::asio::ip::tcp::endpoint(boost::asio::ip::tcp::v4(), port);
@@ -191,7 +193,7 @@ namespace SimpleWeb {
                     boost::asio::streambuf streambuf;
                     std::ostream content(&streambuf);
                     
-                    size_t length;
+                    std::streamsize length;
                     std::string buffer;
                     do {
                         size_t bytes_transferred = boost::asio::read_until(*socket, response->content_buffer, "\r\n");
@@ -199,7 +201,7 @@ namespace SimpleWeb {
                         getline(response->content, line);
                         bytes_transferred-=line.size()+1;
                         line.pop_back();
-                        length=stoull(line, 0, 16);
+                        length=stol(line, 0, 16);
             
                         size_t num_additional_bytes=response->content_buffer.size()-bytes_transferred;
                     
@@ -208,7 +210,7 @@ namespace SimpleWeb {
                                 boost::asio::transfer_exactly(2+length-num_additional_bytes));
                         }
 
-                        buffer.resize(length);
+                        buffer.resize(static_cast<size_t>(length));
                         response->content.read(&buffer[0], length);
                         content.write(&buffer[0], length);
             
@@ -257,4 +259,4 @@ namespace SimpleWeb {
     };
 }
 
-#endif	/* CLIENT_HTTP_HPP */
\ No newline at end of file
+#endif	/* CLIENT_HTTP_HPP */
diff --git a/client_https.hpp b/client_https.hpp
index f6fb865..1a15747 100644
--- a/client_https.hpp
+++ b/client_https.hpp
@@ -28,7 +28,7 @@ namespace SimpleWeb {
                 asio_context.load_verify_file(verify_file);
             
             socket=std::make_shared<HTTPS>(asio_io_service, asio_context);
-        };
+        }
 
     private:
         boost::asio::ssl::context asio_context;
@@ -49,4 +49,4 @@ namespace SimpleWeb {
     };
 }
 
-#endif	/* CLIENT_HTTPS_HPP */
\ No newline at end of file
+#endif	/* CLIENT_HTTPS_HPP */
diff --git a/http_examples.cpp b/http_examples.cpp
index 664763e..d1119ca 100644
--- a/http_examples.cpp
+++ b/http_examples.cpp
@@ -102,7 +102,7 @@ int main() {
                     
                     if(ifs) {
                         ifs.seekg(0, ios::end);
-                        size_t length=ifs.tellg();
+                        auto length=ifs.tellg();
                         
                         ifs.seekg(0, ios::beg);
                         
@@ -111,14 +111,14 @@ int main() {
                         //read and send 128 KB at a time
                         const size_t buffer_size=131072;
                         vector<char> buffer(buffer_size);
-                        size_t read_length;
+                        streamsize read_length;
                         try {
                             while((read_length=ifs.read(&buffer[0], buffer_size).gcount())>0) {
                                 response.write(&buffer[0], read_length);
                                 response.flush();
                             }
                         }
-                        catch(const exception &e) {
+                        catch(const exception &) {
                             cerr << "Connection interrupted, closing file" << endl;
                         }
 
diff --git a/https_examples.cpp b/https_examples.cpp
index 2d05146..2e9d8b5 100644
--- a/https_examples.cpp
+++ b/https_examples.cpp
@@ -102,7 +102,7 @@ int main() {
                     
                     if(ifs) {
                         ifs.seekg(0, ios::end);
-                        size_t length=ifs.tellg();
+                        auto length=ifs.tellg();
                         
                         ifs.seekg(0, ios::beg);
                         
@@ -111,14 +111,14 @@ int main() {
                         //read and send 128 KB at a time
                         const size_t buffer_size=131072;
                         vector<char> buffer(buffer_size);
-                        size_t read_length;
+                        streamsize read_length;
                         try {
                             while((read_length=ifs.read(&buffer[0], buffer_size).gcount())>0) {
                                 response.write(&buffer[0], read_length);
                                 response.flush();
                             }
                         }
-                        catch(const exception &e) {
+                        catch(const exception &) {
                             cerr << "Connection interrupted, closing file" << endl;
                         }
         
diff --git a/server_http.hpp b/server_http.hpp
index 51f4a4f..557c219 100644
--- a/server_http.hpp
+++ b/server_http.hpp
@@ -17,6 +17,8 @@ namespace SimpleWeb {
     template <class socket_type>
     class ServerBase {
     public:
+        virtual ~ServerBase() {}
+
         class Response : public std::ostream {
             friend class ServerBase<socket_type>;
         private:
@@ -101,7 +103,7 @@ namespace SimpleWeb {
                     remote_endpoint_address=socket.lowest_layer().remote_endpoint().address().to_string();
                     remote_endpoint_port=socket.lowest_layer().remote_endpoint().port();
                 }
-                catch(const std::exception& e) {}
+                catch(const std::exception&) {}
             }
         };
         
@@ -195,16 +197,16 @@ namespace SimpleWeb {
         boost::asio::ip::tcp::acceptor acceptor;
         std::vector<std::thread> threads;
         
-        size_t timeout_request;
-        size_t timeout_content;
+        long timeout_request;
+        long timeout_content;
         
-        ServerBase(unsigned short port, size_t num_threads, size_t timeout_request, size_t timeout_send_or_receive) : 
+        ServerBase(unsigned short port, size_t num_threads, long timeout_request, long timeout_send_or_receive) :
                 config(port, num_threads), acceptor(io_service),
                 timeout_request(timeout_request), timeout_content(timeout_send_or_receive) {}
         
         virtual void accept()=0;
         
-        std::shared_ptr<boost::asio::deadline_timer> set_timeout_on_socket(std::shared_ptr<socket_type> socket, size_t seconds) {
+        std::shared_ptr<boost::asio::deadline_timer> set_timeout_on_socket(std::shared_ptr<socket_type> socket, long seconds) {
             std::shared_ptr<boost::asio::deadline_timer> timer(new boost::asio::deadline_timer(io_service));
             timer->expires_from_now(boost::posix_time::seconds(seconds));
             timer->async_wait([socket](const boost::system::error_code& ec){
@@ -217,7 +219,7 @@ namespace SimpleWeb {
             return timer;
         }
         
-        std::shared_ptr<boost::asio::deadline_timer> set_timeout_on_socket(std::shared_ptr<socket_type> socket, std::shared_ptr<Request> request, size_t seconds) {
+        std::shared_ptr<boost::asio::deadline_timer> set_timeout_on_socket(std::shared_ptr<socket_type> socket, std::shared_ptr<Request> request, long seconds) {
             std::shared_ptr<boost::asio::deadline_timer> timer(new boost::asio::deadline_timer(io_service));
             timer->expires_from_now(boost::posix_time::seconds(seconds));
             timer->async_wait(request->strand.wrap([socket](const boost::system::error_code& ec){
@@ -266,7 +268,7 @@ namespace SimpleWeb {
                         try {
                             content_length=stoull(it->second);
                         }
-                        catch(const std::exception &e) {
+                        catch(const std::exception &) {
                             return;
                         }
                         if(content_length>num_additional_bytes) {
@@ -367,7 +369,7 @@ namespace SimpleWeb {
                 try {
                     resource_function(response, request);
                 }
-                catch(const std::exception& e) {
+                catch(const std::exception&) {
                     return;
                 }
                 
@@ -375,7 +377,7 @@ namespace SimpleWeb {
                     try {
                         response.flush();
                     }
-                    catch(const std::exception &e) {
+                    catch(const std::exception &) {
                         return;
                     }
                 }
@@ -385,7 +387,7 @@ namespace SimpleWeb {
                 try {
                     http_version=stof(request->http_version);
                 }
-                catch(const std::exception &e) {
+                catch(const std::exception &) {
                     return;
                 }
                 
@@ -408,7 +410,7 @@ namespace SimpleWeb {
     template<>
     class Server<HTTP> : public ServerBase<HTTP> {
     public:
-        Server(unsigned short port, size_t num_threads=1, size_t timeout_request=5, size_t timeout_content=300) : 
+        Server(unsigned short port, size_t num_threads=1, long timeout_request=5, long timeout_content=300) :
                 ServerBase<HTTP>::ServerBase(port, num_threads, timeout_request, timeout_content) {}
         
     private:
diff --git a/server_https.hpp b/server_https.hpp
index 097ac25..3972475 100644
--- a/server_https.hpp
+++ b/server_https.hpp
@@ -11,7 +11,7 @@ namespace SimpleWeb {
     class Server<HTTPS> : public ServerBase<HTTPS> {
     public:
         Server(unsigned short port, size_t num_threads, const std::string& cert_file, const std::string& private_key_file,
-                size_t timeout_request=5, size_t timeout_content=300, 
+                long timeout_request=5, long timeout_content=300,
                 const std::string& verify_file=std::string()) : 
                 ServerBase<HTTPS>::ServerBase(port, num_threads, timeout_request, timeout_content), 
                 context(boost::asio::ssl::context::sslv23) {
```

What are your opinions on this?

**Comment by drpatrik** [comment]
Very nice much, much better. 

The shadowing issue has nothing to do with google C style and I believe that there is no standard or programming style that encourage shadowing even though CppCore is agnostic to the subject of naming. I respect if you do not want to use "_" or any other type of adornment of member variables but it would be really nice if we could find a solution. Where we do not have to allow shadowing.

**Comment by eidheim** [comment]
I pushed the diff above, with some slight changes. For now its with still warning options `-Wall`, but that is to supress warning messages from boost on some platforms. 

I'll have to think a bit more on the shadow issue, but in general I'm fond of as modern C++ code as possible. The prefixes/postfixes feels like something from the pre2000 era, and as far as I understand it, it is to avoid confusion. With modern IDE's (like [juCi++](https://github.com/cppit/jucipp)) it should not be an issue in my opinion. Although, I'm open for further discussion!

**Comment by drpatrik** [comment]
I respect any decision you take. However shadowing can introduce bugs and it also quite nice from a readability perspective to know if a variable is declared in local scope or on a class level scope. We have about 80,000 lines of C++11/14 code developed during the last 3 years so I like to see our code base as pretty modern :-)

**Comment by jeffreyscottgraham** [comment]
I also would prefer no warnings.

Regarding 3rd party libs and their warnings, I suggest if possible to:
1) use "-isystem <dir>" inplace of "-I <dir>" for the third party libs such as boost
2) in your source use "#include <dir>" for 3rd party and system headers (using < and >)
3) in your source use "#include "dir" for your own project headers (using ")

**Comment by eidheim** [comment]
@jeffreyscottgraham thank you, that helped. Fixed in the commit above.

**Comment by eidheim** [comment]
I think I'm pretty stuck on the issue on shadowing. There really is no good solution to this as far as I see it, unless of course you want to add pre/postfixes to either parameters or member variables, and thus enforcing a specific style. If https://github.com/isocpp/CppCoreGuidelines adds a section on this in the future, which I doubt they will, I'll of course follow them.

I instead propose you use `include_directories(SYSTEM ...)` when including this library in your projects.

**Comment by drpatrik** [comment]
Your proposed solution will work for us.

**Comment by jeffreyscottgraham** [comment]
Closed maybe, but the shadow warnings, and most all compiler warnings in general, have absolutely nothing to do with STYLE. All warnings should be addressed and avoided. IMO shadowing leads
to increased maintenance and congnitive overhead because eventually the wrong-scoped version will be misused/mis-assumed.

**Pull request closed without merging**
