### PR TITLE
Added support for HTTP caching in the https example

### PR DESCRIPTION
**Pull request by sebt3**
Takes number 2.
Using your crypto namespace md5 function this time.

### CODE REVIEW

**Comment by sebt3** [comment]
although it's a bit crazy to not expect openssl for a https server :P

**Comment by eidheim** [comment]
Great, I just added stream versions of the Crypto hash functions so I'll probably do the following changes after I merge this PR:
* Use stream version of Crypto::md5 when calculating hash of a file. This in case the file is large, and thus memory consumption is improved
* Remove ifdefs from https_examples

**Comment by eidheim** [comment]
I decided to have this functionality disabled by default. The reasons are:
* Cache-Control might lead to confusion when old web pages are shown instead of new versions
* ETag introduces an overhead, especially for small files over fast networks.

**Comment by sebt3** [comment]
yes sure :) anyway, it was just to show here how to implement as it's rather easy.

**Pull request merged**
