### PR TITLE
Use unordered_multimap instead of unordered_map

### PR DESCRIPTION
**Pull request by chmike**
The changes also include fixes to get rid of warnings.

### CODE REVIEW

**Comment by eidheim** [comment]
Sorry, I waited with the merge since not all of the tests compiled. Thus, backward compatibility was broken, and I wanted to see if this could be fixed in some way. Not sure, however, if implementing operator[] for the multimap is a good choice. Maybe breaking backward compatibility is the best choice in this case.

**Comment by chmike** [comment]
Indeed, this change breaks backward compatibility. I did other few changes: 
* store header keys in lower case
* use boost::filesystem to access the file to send
* store remote endpoint in the request so user can get the client address (needed for session_id)
* add Content-type to responses

I'm not experience enough with github to know how to offer these changes as independent pull requests. Beside, I want to go on with the development. 

Your mastering of asio is impressive. Your web server is indeed simple and does the job.

**Comment by eidheim** [comment]
Thank you, your changes are most welcome. 

I think if I am faster with the merges you can create several pull requests, but only one each time, but I am not 100% sure. After you create a pull request, any commits you do will also become part of that pull request. Sadly, I am not that experienced in Github either.

**Comment by chmike** [comment]
Not sure if you will agree with all the changes I do. For instance I'm starting to use boost::log to produce log information on the server side. It is helpful for feedback and debugging the server. It should be made asynchronous.

**Comment by chmike** [comment]
Hello I have cloned your repository locally and created a branch 'chm-features' in witch I implemented many different changes. If you give me write permission to this project I can upload the branch for merge request. I didn't use boot log in this code.

The changes are 
* made the endpoint info available to the user for http and https. It is usually needed to generate the session id. 
* created a http_status(status) iomanip in the example files which is easier to use in my opinion.
* created a send_file function in the example files that use boost_filesystem which is  claimed to be portable. I only tested the code on linux.
* use unordered_multimap to store the request headers
* store header keys in lowercase
* added a 404.html with an image returned if a requested file resource (default) is not found.

**Comment by eidheim** [comment]
Interesting changes, most likely I will merge them to the master branch, but would you mind creating a pull request to the "chm-features"-branch I just created? You can for instance create a similar branch, or use your master branch, push your changes to this, and create a pull request to my chm-features-branch.

**Pull request closed without merging**
