### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by burner**
I really like this server. Only fast part in the description was not so true. regex killed it.

*I created a handwritten the http parser. (nearly 4x speedup with index.html callback)
**  You can test this as the parser is a function pointer, see the server_http constructor.
* Created a vector based callback matcher without regex
* I changed the default callback to one get and one post callback
* alot more

### CODE REVIEW

**Comment by eidheim** [comment]
Hi, and thank you. 

This pull request is quite large, and I am working on a larger update, including a similar speed up. I also noticed that especially GCC had a slow regex-engine. Additionally, turning on the no_delay option on the sockets helped on Linux (Debian testing). Also have added support for flushing the outstream both synchronously and asynchronously. Will hopefully upload the changes in a few days.

**Comment by burner** [comment]
Sounds nice. It is not only the regex-engine. The regex-machines are build for every new request. Also the unordered map is slow to iterate even with the iterator vector. simple vector string compare is hard to beat. Anyway looking forward to your update.

**Comment by burner** [comment]
what would be really awesome is, if we could get async io in. the html publish part is totally hd limited in my tests.

**Comment by eidheim** [comment]
Think it might be better to use unordered_map::find instead of using vector to find the non-regex resources. At least if one have many/long/similar resources that has to be compared to the request-path.

Almost done now, though in my tests flushing asynchronously does not yield much improvement when sending large files. Though maybe you are more lucky. But if one needs to process computationally expensive tasks and send alot of data, and can do this simultaneously, one might see an improvement. Though, at least the file upload (default_resource from the examples) can now handle files that are larger than available memory.

Might upload the changes Tomorrow.

**Comment by burner** [comment]
an unordered_map is properly better for many entry points for anything less than a few cache lines IMO vector will win. (benchmarking will show)

looking forward to see the commit

**Comment by eidheim** [comment]
Finally I've commited the updates. I did keep unordered_map on both path and method search since it required fewer code lines. Hopefully you will not see a difference in the request-times. Also using unordered_map scales better if one decides to use a large number of paths and methods (many different request methods are highly unlikely though). However, I might decide to change it depending on benchmarks. 

The regex-engines are now built in Server::start like you suggested. And most of the regex-use is replaced by string-operations.

**Comment by burner** [comment]
httperf --server=localhost --port=8080 --uri=/match/1337 --num-conns=200 --num-calls=10000
Your version: Request rate: 26403.9 req/s
Me PR: Request rate: 45035.6 req/s

httperf --server=localhost --port=8080 --uri=/index.html --num-conns=200 --num-calls=10000
Your version: Request rate: 12476.9 req/s
Me PR: Request rate: 18738.5 req/s

I haven't run valgrind yet, but I guess it is the same problem as before, anyway enormous speedup.
I'm not sure what to do next with this PR...

**Comment by burner** [comment]
just for comparison the old version made:

Request rate: 1880.4 req/s for --uri=/match/1337
Request rate: 1802.1 req/s for --uri=/index.html

**Comment by eidheim** [comment]
I feel bad for not accepting your PR, but there were too many large changes, and backward compatibility was broken. Trying not to break the backward compatibility too often, and hopefully never again. For instance, if one does decide to go for vector instead of unordered_map to find resources, it is possible to do this without affecting the examples. That said, your input, fork and testing has been extremely helpful, and much of the improvements would maybe never have happened without it. I'm not a GitHub expert, but is there a way to add you to the Contributors list without accepting the PR? Or maybe add you as contributor on the last commit?

On the benchmarks:
The default_resource httperf-testing is highly dependent on the variable buffer_size. Also, your PR do not use regex on the /match resource (thus it is more difficult to make resources that process i.e.: /match/123/and/1337), and do you use the same number of threads in both servers? However, the request rate is slightly (10-20% maybe) affected sadly by the code to achieve synchronous and asynchronous flushing.

**Comment by burner** [comment]
don't sweat it, I had fun fiddling with it.

maybe we should build something together. do you have anything nice to work with cookies. I don't.

on the benchmark:
Yes of course, my match stuff is cheating a bit.
I use four threads on both, on a four core machine.

**Comment by burner** [comment]
I'm closing this, thanks

**Pull request closed without merging**
