### PR TITLE
Chm features

### PR DESCRIPTION
**Pull request by chmike**
The changes are

*    made the endpoint info available to the user for http and https. It is usually needed to generate the session id.
*    created a http_status(status) iomanip in the example files which is easier to use in my opinion.
*    created a send_file function in the example files that use boost_filesystem which is claimed to be portable. I only tested the code on linux.
*    use unordered_multimap to store the request headers
*    store header keys in lowercase
*    added a 404.html with an image returned if a requested file resource (default) is not found.

I didn't merge the commits so you can cherry pick what you want.

### CODE REVIEW

**Comment by eidheim** [comment]
Several great changes here, thank you. Will look through them more thoroughly before merging the branch to master. The example files get abit larger, and that is my main concern, but still its great additions. 

Also, is it enough to store the remote_endpoint().address() and remote_endpoint().port() in the Request class? Such as for instance is done in: https://github.com/eidheim/Simple-WebSocket-Server/blob/master/server_ws.hpp (here in the Connection class, see line 48).

**Comment by eidheim** [comment]
Also got some error messages while compiling with g++-4.9, but I will figure them out Tomorrow. What compiler are you using?

**Comment by chmike** [comment]
I checked the socket API again and noticed that the socket class has 
also a lowest_layer() fuction. So we can avoid passing the end point as 
argument of the read_request_and_content() method. This is a mistake in 
my code.

The other information is the local endpoint. It is much less frequently 
needed, but it could on a host with multiple network cards. The user may 
want to know on which interface the request is coming.

It would be good if we could avoid calling remote_endpoint() and 
local_endpoint() on every call. Could we store a copy of the low level 
socket in the request ? The user may then call remote_endpoint() and 
local_endpoint() himself as needed.


Le 16/06/2015 22:28, Ole Christian Eidheim a écrit :
>
> Several great changes here, thank you. Will look through them more 
> thoroughly before merging the branch to master. The example files get 
> abit larger, and that is my main concern, but still its great additions.
>
> Also, is it enough to store the remote_endpoint().address() and 
> remote_endpoint().port() in the Request class? Such as for instance is 
> done in: 
> https://github.com/eidheim/Simple-WebSocket-Server/blob/master/server_ws.hpp 
> (here in the Connection class, see line 48).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/eidheim/Simple-Web-Server/pull/10#issuecomment-112559235>.
>

-- 
Bien cordialement,

Ch.Meessen

**Comment by chmike** [comment]
I used the latest QtCreator 3.3.1 to develop and test. It uses

GNU C++ (Ubuntu 4.9.2-10ubuntu13) version 4.9.2 (x86_64-linux-gnu)


This is the command it used to compile

g++ -Wl,-rpath,/opt/Qt5.4.1/5.4/gcc_64 -o Simple-Web-Server 
http_examples.o -pthread -lboost_thread -lboost_coroutine -lboost_system 
-lboost_chrono -lboost_context -lboost_date_time -lboost_filesystem 
-lboost_program_options -lboost_log


I also tested the command you gave in the readme. It compiled without 
error. This the command I used.

g++ -O3 -std=c++11 http_examples.cpp -lboost_system -lboost_thread 
-lboost_coroutine -lboost_context -o http_examples -pthread 
-lboost_filesystem

Note that we now have to link with -lboost_filesystem.

Le 16/06/2015 22:34, Ole Christian Eidheim a écrit :
>
> Also got some error messages while compiling with g++-4.9, but I will 
> figure them out Tomorrow. What compiler are you using?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/eidheim/Simple-Web-Server/pull/10#issuecomment-112560850>.
>

-- 
Bien cordialement,

Ch.Meessen

**Pull request merged**
