### PR TITLE
Adding a reload method to allow new method added after a start()

### PR DESCRIPTION
**Pull request by sebt3**
Title say pretty much all.

### CODE REVIEW

**Comment by eidheim** [comment]
Changing the resources during runtime of the server is problematic as the resources have to be protected by mutex locks. This would slow down the processing, especially when running a multiple threading strategy. 

However, instead of creating new resources on the fly, you can define a resource with an appropriate regex and use this for new paths that you might want to setup during runtime of the server.

**Comment by sebt3** [comment]
Yeah, I knew this quick hack wouldnt make it as it lack the requiered mutex locks.
Somehow, I realy need to add new regex to the list on the fly, and having a broader regex wouldnt make it as the resources added later are plugin-based. I dont have any performance issues (shouldnt exceed 50 query per minut).
Having a slow down while requesting a webserver to reload it's configuration have to be expected, so if the reload function were properly protected by a mutex (with the same things done in the find_resource part) I dont see it as a deal breaker.
Anyway, thanks for your feedback :) I'll try to come up with a solution to my problem that doesn't involve having a "opt_resource.clear();" in the middle of the way.
I can submit either solution here if you want :)

**Comment by sebt3** [comment]
This implementation is simple enough to not requiere such tools imho.

The real (and good) reason why eidheim will not merge this is that because of the mutex, the find_resource method become serialized which will be very bad for high work-load.
At some point i'll probably normalize what my plugin can register and goes the way he suggested to actually revert to his master branch.

**Comment by eidheim** [comment]
@sebt3 You can also skip the resource map entirely and do your own path processing in default_resource. If you let the server run on one thread also, there is no need for mutex locks when you do your own implementation in default_resource. The resource map is only a convenient way for the users of the library so that one does not need to implement their own path processing.

Regarding mutex lock/unlock, I agree with @jeffreyscottgraham that it is safest to always use `lock_guard` or `unique_lock`. `lock_guard` is the simplest one, and might have less overhead than `unique_lock` (I'm not entirely sure if `unique_lock` adds additional assembly instructions on some/all compilers), but `unique_lock` has lock/unlock methods giving you more control when a mutex should be locked and/or unlocked, while at the same time being exception safe.

**Comment by sebt3** [comment]
Ok, I've successfully normalized enough my plugins so I dont need this feature anymore.
I've reverted to your master branch. Feel free to close this pull-request ;)
And thanks for your feedback

**Pull request closed without merging**
