### PR TITLE
BIO_new_mem_buf need a mutable pointer.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by eidheim** [comment]
`BIO_new_mem_buf` is a read only memory BIO, so `const char *` type argument works fine I think.

**Comment by devnexen** [comment]
Ok but the compilation failed for me because of BIO_new_mem_buf signature

**Comment by eidheim** [comment]
Which compiler are you using?

**Comment by eidheim** [comment]
And which openssl version?

**Comment by devnexen** [comment]
gcc 4.9.4 and .... oops just realised it was libressl

**Comment by devnexen** [comment]
I have both openssl and libressl but it s linked to libressl actually

**Pull request closed without merging**
